apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: db
      labels:
        app: db

    spec:
      containers:
        - name: db-app
          env:
            - name: POSTGRES_USER
              value: postgres 
            - name: POSTGRES_PASSWORD
              value: postgres
          image: postgres:9.4
          ports:
            - containerPort: 5432
              name: db
          # imagePullPolicy: Never