apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: vote
  labels:
    app: vote

spec:
  template:
    metadata:
      name: vote
      labels:
        app: vote

    spec:
      containers:
        - name: voting-app
          image: voting-app
          ports:
            - containerPort: 80
              name: vote
          # imagePullPolicy: Never

  selector:
    matchLabels:
      app: vote

  replicas: 1