apiVersion: v1
kind: Pod 
metadata:
  name: db
  labels:
    app: db

spec:
  containers:
    - name: db-app
      env:
        - name: POSTGRES_USER
          value: postgres 
        - name: POSTGRES_PASSWORD
          value: postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432
          name: db
      # imagePullPolicy: Never