apiVersion: v1
kind: Pod 
metadata:
  name: result
  labels:
    app: result

spec:
  containers:
    - name: result-app
      image: result-app
      ports:
        - containerPort: 80
          name: result
      # imagePullPolicy: Never