apiVersion: v1
kind: Pod 
metadata:
  name: vote
  labels:
    app: vote

spec:
  containers:
    - name: voting-app
      image: voting-app
      ports:
        - containerPort: 80
          name: vote
      # imagePullPolicy: Never